version: "3.1"
services:
  node:
    image: node:15.2.1
    container_name: node
    user: node
    depends_on:
      - mongo
    working_dir: /home/node/app
    volumes:
      - ./minimalist_bank_app:/home/node/app
    ports:
      - "3000:3000"
    command: "npm start"
    networks:
      - bank_network

  mongo:
    image: mongo:4.4.1
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - bank_network

networks:
  bank_network: {}
